### ISSUE TITLE
newer maps missing

### ISSUE THREAD

**Issue by icekxd** [randombits-dev/snowrunner-save-editor#74]
Hi, great job on this tool - it is working flawlessly.

Would you be able to update it to include the missing maps i.e. British Columbia?

Thanks!

**Comment by Sail0609** [comment]
Request for new map update, thanks!

**Comment by Guardempire** [comment]
Need them urgently!! :)

**Comment by nienow** [comment]
I added Ontario and British Columbia. Can someone verify it is working properly? I haven't played the game in a while.

**Comment by Sail0609** [comment]
> 我添加了安大略省和不列颠哥伦比亚省。有人可以验证它是否正常工作吗？我已经有一段时间没有玩这个游戏了。

Yes, they work now, and I'm glad you didn't give up on this project!

**Comment by nienow** [comment]
@Sail0609 Thank you for testing.
